# Generated by Django 5.0 on 2024-01-02 09:01

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, upload_to=auctions.models.image_path),
        ),
    ]
