# Generated by Django 5.0 on 2023-12-29 19:25

import auctions.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['start']},
        ),
        migrations.AddField(
            model_name='listing',
            name='duration',
            field=models.PositiveIntegerField(choices=[(1, '1 hour'), (3, '3 hours'), (12, '12 hours')], default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, upload_to=auctions.models.image_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=0.01)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
