# Generated by Django 5.0 on 2023-12-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_price_bids_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='upload',
            new_name='image',
        ),
    ]
